# Generated by Django 4.2.5 on 2023-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
