# Generated by Django 4.2.5 on 2023-10-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_placeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Place',
            name='placeid',
        )
    ]