# Generated by Django 4.2.5 on 2023-10-17 12:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_options_alter_placeimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(default=500),
        ),
    ]
