# Generated by Django 4.2.5 on 2023-10-17 12:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='content',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
    ]
