# Generated by Django 4.2.5 on 2023-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_placeimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImageDouble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('number', models.PositiveIntegerField(db_index=True, verbose_name='Номер изображения')),
            ],
        ),
    ]
