# Generated by Django 4.2.5 on 2023-10-24 19:46

from django.db import migrations

# Generated by Django 4.2.5 on 2023-10-24 19:35

from django.db import migrations


def copy_placeimage_to_placeimagedouble(apps, schema_editor):
    PlaceImage = apps.get_model('places', 'PlaceImage')
    PlaceImageDouble = apps.get_model('places', 'PlaceImageDouble')
    place_images = PlaceImage.objects.all()
    for place_image in place_images.iterator():
        PlaceImageDouble.objects.get_or_create(image=place_image.image, number=place_image.number)


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0013_placeimagedouble'),
    ]

    operations = [
        migrations.RunPython(copy_placeimage_to_placeimagedouble),
    ]
