# Generated by Django 4.2.5 on 2023-10-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20231024_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceImageDouble',
        ),
    ]
