# Generated by Django 4.2.5 on 2023-10-25 12:34

from django.db import migrations
from django.db.models import Q


def replaces_none_with_empty_string(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Place.objects.filter(short_description=None).update(short_description='')
    Place.objects.filter(long_description=None).update(long_description='')


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0017_alter_place_long_description_alter_placeimage_number'),
    ]

    operations = [
        migrations.RunPython(replaces_none_with_empty_string),
    ]
