# Generated by Django 4.2.5 on 2023-10-26 12:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_auto_20231026_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceDouble',
        ),
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Короткое описание'),
        ),
    ]
