# Generated by Django 4.2.5 on 2023-10-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_delete_placedouble_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Номер изображения'),
        ),
    ]
